### ISSUE TITLE
db.add_model() not responding

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sih4sing5hong5/voiceid#28]
```
Hi,

I recently switched to Ubuntu 13.10. After installing the Voiceid, I tested my 
samples following the the few codes given for usage on the installation page. 
Some samples were diarized while others were not. I don't know why.

I however, proceeded to trying out the library. When I get to the add_model to 
create/train my voices in the database, it seems to hang or take forever. I am 
stuck at this point. Any help will be appreciated. 


```

Original issue reported on code.google.com by `kaggsmag...@gmail.com` on 14 Feb 2014 at 3:13

**Comment by vikascm** [comment]
Hi,

I am using Ubuntu 16.04. I am facing the same issue when I try to add model to db using db.add_model(). The wiki document of VoiceID (https://code.google.com/archive/p/voiceid/wikis/UsingLibrary.wiki) says that even if no model is added, it still gives output with unknown identifier. I tried implementing that but again the same error. 

The code is the following :

from voiceid.sr import Voiceid 
from voiceid.db import GMMVoiceDB

db = GMMVoiceDB('db_voice')

db.add_model('speaker1','speaker_one')

v = Voiceid(db,'convo1.mp3')

v.extract_speakers()

for c in v.get_clusters(): 
    cluster = v.get_cluster(c) 
    print cluster 
    cluster.print_segments()

The error i get for add_model() step is the following :

Traceback (most recent call last):
  File "voiceid1.py", line 6, in <module>
    db.add_model('speaker1','speaker_one')
  File "/usr/local/lib/python2.7/dist-packages/voiceid/db.py", line 187, in add_model
    fm.build_gmm(basefilename, identifier)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 315, in build_gmm
    diarization_standard(filebasename)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 524, in diarization_standard
    + filebasename)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/utils.py", line 79, in start_subprocess
    raise err
OSError: Subprocess <subprocess.Popen object at 0x7f9564d80710> closed unexpectedly [java -Xmx2048m -jar /usr/local/share/voiceid/LIUM_SpkDiarization-4.7.jar fr.lium.spkDiarization.system.Diarization --fInputMask=%s.wav --sOutputMask=%s.seg --doCEClustering /home/vikas/python_codes/diarize/speaker1]

The error when I get for v.extract_speakers() step is the following :

converting_file
Traceback (most recent call last):
  File "voiceid1.py", line 10, in <module>
    v.extract_speakers()
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 988, in extract_speakers
    self._to_wav()
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 697, in _to_wav
    fname = fm.file2wav(self.get_filename()) 
  File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 84, in file2wav
    + "wavenc ! filesink location=" + name + ".wav ")
  File "/usr/local/lib/python2.7/dist-packages/voiceid/utils.py", line 79, in start_subprocess
    raise err
OSError: Subprocess <subprocess.Popen object at 0x7f85f32e17d0> closed unexpectedly [gst-launch filesrc location='convo1.mp3' ! decodebin ! audioresample ! 'audio/x-raw-int,rate=16000' ! audioconvert ! 'audio/x-raw-int,rate=16000,depth=16,signed=true,channels=1' !wavenc ! filesink location=convo1.wav ]

I use java version "1.8.0_101". Python 2.7.12. 

I even ran the jar file out of Python on terminal and the output I got is the following :

info[info] 	 ====================================================== 
info[program] 	 name = Diarization
info[info] 	 ------------------------------------------------------ 
info[show] 	 [options] show
info[ParameterFeature-Input] 	 --fInputMask 	 Features input mask = %s.mfcc
info[ParameterFeature-Input] 	 --fInputDesc 	 Features info (type[,s:e:ds:de:dds:dde,dim,c:r:wSize:method]) = audio2sphinx,1:1:0:0:0:0,13,0:0:0:0
info[ParameterFeature-Input] 	 	 type [sphinx,spro4,htk,gztxt,audio2sphinx] = audio2sphinx (4)
info[ParameterFeature-Input] 	 	 static [0=not present,1=present ,3=to be removed] = 1
info[ParameterFeature-Input] 	 	 energy [0,1,3] = 1
info[ParameterFeature-Input] 	 	 delta [0,1,2=computed on the fly,3] = 0
info[ParameterFeature-Input] 	 	 delta energy [0,1,2=computed on the fly,3] = 0
info[ParameterFeature-Input] 	 	 delta delta [0,1,2,3] = 0
info[ParameterFeature-Input] 	 	 delta delta energy [0,1,2,3] = 0
info[ParameterFeature-Input] 	 	 file dim = 13
info[ParameterFeature-Input] 	 	 normalization, center [0,1] = 0
info[ParameterFeature-Input] 	 	 normalization, reduce [0,1] = 0
info[ParameterFeature-Input] 	 	 normalization, window size = 0
info[ParameterFeature-Input] 	 	 normalization, method [0 (segment), 1 (cluster), 2 (sliding), 3 (warping)] =0
info[ParameterFeature-Input] 	 --fInputMemoryOccupationRate 	 memory occupation rate of the feature in the java virtual machine = 0.8
info[info] 	 ------------------------------------------------------ 
info[ParameterSegmentationFile-Input] 	 --sInputMask 	 segmentation mask = 
info[ParameterSegmentationFile-Input ([seg,bck,ctl,saus.seg,seg.xml,media.xml],[ISO-8859-1,UTF8])] 	 --sInputFormat 	 segmentation format = seg,ISO-8859-1
info[ParameterSegmentationFile-Input2] 	 --sInput2Mask 	 segmentation mask = 
info[ParameterSegmentationFile-Input2 ([seg,bck,ctl,saus.seg,seg.xml,media.xml],[ISO-8859-1,UTF8])] 	 --sInput2Format 	 segmentation format = seg,ISO-8859-1
info[ParameterSegmentationFile-Output] 	 --sOutputMask 	 segmentation mask = %s.out.seg
info[ParameterSegmentationFile-Output ([seg,bck,ctl,saus.seg,seg.xml,media.xml],[ISO-8859-1,UTF8])] 	 --sOutputFormat 	 segmentation format = seg,ISO-8859-1
info[info] 	 ------------------------------------------------------ 
info[ParameterSystem] 	 --system [baseline,10s]= baseline
info[ParameterSystem] 	 --doCEClustering = false
info[ParameterSystem] 	 --doTuning = false
info[ParameterSystem] 	 --thresholds = l=2.0, h=3.0, d=250.0, c=1.7:5.0
info[ParameterSystem] 	 --saveAllStep = false
info[ParameterSystem] 	 --loadInputSegmentation = false
info[info] 	 ------------------------------------------------------ 


Thank you for your help in advance.

**Comment by sih4sing5hong5** [comment]
I suggest just printing `args` in https://github.com/sih4sing5hong5/voiceid/blob/master/src/voiceid/utils.py#L53, and comparing it with the one you executed on terminal.

**Comment by vikascm** [comment]
@sih4sing5hong5 Thank you very much for your response.

I tried printing `args` in both `if` and `else` case as you suggested but the execution is not at all going to that segment of code. I still get the same error. I am trying to figure out where exactly the error is being thrown. 

P.S I am sorry for the late response

**Comment by sih4sing5hong5** [comment]
If it works in your terminal, try the link about [Popen](http://stackoverflow.com/a/901992/3640653)
